---
author:
- name: Raymond L. Tremblay
  affiliation: Universidad de Puerto Rico
  email: raymond.tremblay@upr.edu
date: '`r format(Sys.Date())`'
title: Quantitative Agricultural Economics
site: bookdown::bookdown_site
output:
  html_document:
    keep_tex: true
    theme: lumen
    highlight: tango
#    includes:
#      after_body: footer.tex
biblio-style: apalike
---
  








#--- 
#title: "Quantitative Agricultural Economics"
#author: "Raymond L. Tremblay"
#date: "`r Sys.Date()`"
#site: bookdown::bookdown_site

#---

# Daily Activities

This is a bookdown project that will be used in a workshop for faculty and graduate students on Quantitative Agricultural Economics at the University of Puerto Rico-Mayagüez. 


***


Day 1: Introduction to RStudio and available packages

   -⁠ ⁠Interaction with the Platform (Chapter 2)

   -⁠ ⁠How to search and download statistical packages? (Chapter3)

   -⁠ Understand the default programming of statistical packages?

   -  ⁠How to find help?

   - ⁠ ⁠How to upload data, rename variables, delete data, find missing values, view descriptive statistics, view variable types, etc.)

   - Normality tests
      - ⁠Shapiro-Wilk test
      - Anderson-Darling test

   -⁠ t-test

 - ⁠Non- Parametric tests
      - ⁠Kruskal Wallis tests


***
 
Day 2: Data visualization - graphs

  -⁠ ⁠Scatter plot (simple and with multiple variables)

  -⁠ ⁠Scatter plot matrix

  -⁠ ⁠Linear graph (simple and with two variables)

  - Donut Chart (an laternative to Pie charts)

  -⁠ ⁠Histograms (simple and with multiple variables)

•⁠ ⁠Kernel density

•⁠ ⁠Box plot

•⁠ ⁠Other grasph


***
 
Day 3: Econometric models and assumptions

•⁠ ⁠Ordinary least squares regression

•⁠ ⁠Assumption checking

•⁠ ⁠Quantile regression

•⁠ ⁠Logit regression and post-estimation tests/check
       - Percent correct predictions
       - Marginal effects, 
       - Goodness of fit, 
       


***

Day 4: Econometric models and assumptions

•⁠ ⁠Multinomial logit regression and post-estimation tests/checks

•⁠ ⁠Beta regresonsi

